// <auto-generated />
namespace TeamManagementService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedteamtoproject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedteamtoproject));
        
        string IMigrationMetadata.Id
        {
            get { return "201608201205183_changed team to project"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
